// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { IMAGE_FRAMES, getFrameBands, resolveFramed } from './registry';
import { LAYOUTS } from '../layouts/registry';

const S = 4; // recommended artwork scale: 4 px per layout unit (1536 px wide)

/** Authoring sheet for the PNG artwork. Regenerate with `npm run frame-specs` after changing bands or layouts. */
export function frameSpecsMarkdown(): string {
  const out = [
    '# Frame artwork specs', '',
    '_Generated by `npm run frame-specs` from the layout engine + frame bands. Do not edit by hand._', '',
    `Export each PNG at **${S}× the layout units** (1536 px wide), RGBA, with the photo windows fully **transparent** (alpha 0) and everything else opaque.`,
    'The canvas aspect must match within 1.5% (a test checks any PNG you add). Slot rectangles below are in artwork pixels (x, y, w, h).', ''
  ];
  for (const f of IMAGE_FRAMES) {
    out.push(`## ${f.name} (\`${f.id}\`, folder \`src/assets/frames/${f.image!.dir}/\`)`, '');
    for (const l of LAYOUTS) {
      const L = resolveFramed(l.id, f.id), b = getFrameBands(f, l.id);
      out.push(`### \`${l.id}.png\` — ${L.width * S} × ${L.height * S} px (aspect ${(L.width / L.height).toFixed(4)}), header band ${b.headerHeight * S} px, footer band ${b.footerHeight * S} px`, '');
      L.slots.forEach((s, i) => out.push(`- window ${i + 1}: ${s.x * S}, ${s.y * S}, ${s.w * S} × ${s.h * S}`));
      out.push('');
    }
  }
  return out.join('\n');
}

describe('frame artwork spec sheet', () => {
  it('docs/FRAME-SPECS.md matches the layout engine (run `npm run frame-specs` to refresh)', async () => {
    await expect(frameSpecsMarkdown()).toMatchFileSnapshot('../../docs/FRAME-SPECS.md');
  });
  it('every layout produces at least one window and a positive canvas for each image frame', () => {
    for (const f of IMAGE_FRAMES) for (const l of LAYOUTS) {
      const L = resolveFramed(l.id, f.id);
      expect(L.slots.length).toBeGreaterThan(0);
      expect(L.height).toBeGreaterThan(0);
    }
  });
});
