// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { IMAGE_FRAMES, getFrameBands, resolveFramed } from './registry';
import { LAYOUTS } from '../layouts/registry';

const S = 3; // artwork scale: 3 px per layout unit (1152 px wide, ~ native size of the supplied designs)

/** Authoring sheet for the PNG artwork. Regenerate with `npm run frame-specs` after changing bands or layouts. */
export function frameSpecsMarkdown(): string {
  const out = [
    '# Frame artwork specs', '',
    '_Generated by `npm run frame-specs` from the layout engine + frame bands. Do not edit by hand._', '',
    `Artwork is built at **${S}× the layout units** (1152 px wide), RGBA, with the photo windows fully **transparent** (alpha 0) and everything else opaque.`,
    'The canvas aspect must match within 1.5% (a test checks any PNG you add). Slot rectangles below are in artwork pixels (x, y, w, h).', ''
  ];
  for (const f of IMAGE_FRAMES) {
    out.push(`## ${f.name} (\`${f.id}\`, folder \`src/assets/frames/${f.image!.dir}/\`)`, '');
    for (const l of LAYOUTS) {
      const L = resolveFramed(l.id, f.id), b = getFrameBands(f, l.id);
      out.push(`### \`${l.id}.png\` — ${L.width * S} × ${L.height * S} px (aspect ${(L.width / L.height).toFixed(4)}), header band ${b.headerHeight * S} px, footer band ${b.footerHeight * S} px`, '');
      L.slots.forEach((s, i) => out.push(`- window ${i + 1}: ${s.x * S}, ${s.y * S}, ${s.w * S} × ${s.h * S}`));
      out.push('');
    }
  }
  return out.join('\n');
}

/** Machine-readable geometry (layout units @384) consumed by scripts/build-frames.mjs. */
export function frameLayoutsJson(): string {
  const o: Record<string, Record<string, unknown>> = {};
  for (const f of IMAGE_FRAMES) {
    o[f.id] = {};
    for (const l of LAYOUTS) { const L = resolveFramed(l.id, f.id); o[f.id][l.id] = { w: L.width, h: L.height, slots: L.slots.map((s) => [s.x, s.y, s.w, s.h]) }; }
  }
  return JSON.stringify(o, null, 1) + '\n';
}

describe('frame artwork spec sheet', () => {
  it('docs/frame-layouts.json matches the layout engine', async () => {
    await expect(frameLayoutsJson()).toMatchFileSnapshot('../../docs/frame-layouts.json');
  });
  it('docs/FRAME-SPECS.md matches the layout engine (run `npm run frame-specs` to refresh)', async () => {
    await expect(frameSpecsMarkdown()).toMatchFileSnapshot('../../docs/FRAME-SPECS.md');
  });
  it('every layout produces at least one window and a positive canvas for each image frame', () => {
    for (const f of IMAGE_FRAMES) for (const l of LAYOUTS) {
      const L = resolveFramed(l.id, f.id);
      expect(L.slots.length).toBeGreaterThan(0);
      expect(L.height).toBeGreaterThan(0);
    }
  });
});
